### ISSUE TITLE
Suggestion: adding custom sounds

### ISSUE THREAD

**Issue by maxlefou** [Silverfeelin/Starbound-Instrumentalizer#2]
Would it be possible to add a "custom sound" option? Like, where someone can upload a sound (or 8 sounds for the 8 octaves) and then it converts the sounds at the right ogg format and make a completely custom instrument with these sounds.

(found this when I was trying to make my own instrument with a custom sound. Everything works right, except that the instrument doesn't play the song at all. No playing moves, no music notes, no sound. And I have no idea of why... :s )

**Comment by Silverfeelin** [comment]
This isn't really the tool for that!

This tool specifically targets at making custom-looking instruments that work on unmodded servers, by creating custom drawables using directives. It's a neat suggestion, but it'd be a different project and not something I'll be making myself.

Sorry!

**Comment by Vortetty** [comment]
not possible for vanilla, the tuning is predefined for all instruments

**Comment by Silverfeelin** [comment]
Yeah, the solution would be to make a new instrument. At that point it'd be more of a tool to help create an instrument mod, where you can play with the options in a more user-friendly manner. But this isn't that project, and that project wouldn't be vanilla-compatible.

Since this issue is 3 years old I'm going to go ahead and close it now 😉.
